app = "agent-work-bridge-dev"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[mounts]]
  source = "notes_data"
  destination = "/data"

[checks]
  [checks.healthz]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    path = "/health"
